"""paper_bets units

Revision ID: 5b6d508ce8e6
Revises: c8e785f1e415
Create Date: 2026-07-19 23:23:05.299272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b6d508ce8e6'
down_revision: Union[str, None] = 'c8e785f1e415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_bets', sa.Column('units', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_bets', 'units')
    # ### end Alembic commands ###
