"""match_score_log table

Revision ID: 742bed9b24c4
Revises: c842dfb036d9
Create Date: 2026-07-20 00:18:56.733068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '742bed9b24c4'
down_revision: Union[str, None] = 'c842dfb036d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_score_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_ticker', sa.String(length=96), nullable=False),
    sa.Column('event_ticker', sa.String(length=96), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sets_a', sa.Integer(), nullable=False),
    sa.Column('sets_b', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('games_a', sa.Integer(), nullable=False),
    sa.Column('games_b', sa.Integer(), nullable=False),
    sa.Column('scoreline', sa.String(length=96), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scorelog_market_ts', 'match_score_log', ['market_ticker', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scorelog_market_ts', table_name='match_score_log')
    op.drop_table('match_score_log')
    # ### end Alembic commands ###
