"""initial schema

Revision ID: be93d41a9f93
Revises: 
Create Date: 2026-07-19 15:53:02.324776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'be93d41a9f93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_gaps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_ticker', sa.String(length=96), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('gap_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gap_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_gaps_market_ticker'), 'feed_gaps', ['market_ticker'], unique=False)
    op.create_table('ingest_state',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('market_ticks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('market_ticker', sa.String(length=96), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('yes_bid', sa.Integer(), nullable=True),
    sa.Column('yes_ask', sa.Integer(), nullable=True),
    sa.Column('no_bid', sa.Integer(), nullable=True),
    sa.Column('no_ask', sa.Integer(), nullable=True),
    sa.Column('trade_price', sa.Integer(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_ticks_session_id'), 'market_ticks', ['session_id'], unique=False)
    op.create_index('ix_ticks_market_ts', 'market_ticks', ['market_ticker', 'ts'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tour', sa.String(length=8), nullable=False),
    sa.Column('sackmann_id', sa.BigInteger(), nullable=True),
    sa.Column('api_tennis_id', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('hand', sa.String(length=4), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('ioc', sa.String(length=8), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour', 'sackmann_id', name='uq_players_tour_sackmann')
    )
    op.create_index('ix_players_api_tennis', 'players', ['tour', 'api_tennis_id'], unique=False)
    op.create_index(op.f('ix_players_normalized_name'), 'players', ['normalized_name'], unique=False)
    op.create_table('state_inference_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_ticker', sa.String(length=96), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('inferred_state', sa.String(length=16), nullable=False),
    sa.Column('inferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_state', sa.String(length=16), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_time_seconds', sa.Float(), nullable=True),
    sa.Column('hit', sa.Boolean(), nullable=True),
    sa.Column('session_had_gap', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_inference_log_market_ticker'), 'state_inference_log', ['market_ticker'], unique=False)
    op.create_index(op.f('ix_state_inference_log_session_id'), 'state_inference_log', ['session_id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tour', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('surface', sa.String(length=16), nullable=True),
    sa.Column('level', sa.String(length=8), nullable=True),
    sa.Column('draw_size', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour', 'source', 'source_key', name='uq_tournaments_key')
    )
    op.create_table('match_review_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('raw_name', sa.String(length=256), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_player_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tour', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_key', sa.String(length=96), nullable=False),
    sa.Column('tournament_id', sa.BigInteger(), nullable=True),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('loser_id', sa.BigInteger(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('round', sa.String(length=8), nullable=True),
    sa.Column('best_of', sa.Integer(), nullable=True),
    sa.Column('score_raw', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('sets_won_winner', sa.Integer(), nullable=True),
    sa.Column('sets_won_loser', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(length=16), nullable=True),
    sa.Column('tourney_level', sa.String(length=8), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_key', name='uq_matches_source_key')
    )
    op.create_index('ix_matches_loser_date', 'matches', ['loser_id', 'match_date'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_index('ix_matches_winner_date', 'matches', ['winner_id', 'match_date'], unique=False)
    op.create_table('player_aliases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alias_normalized', sa.String(length=256), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_normalized', 'source', name='uq_alias_source')
    )
    op.create_index(op.f('ix_player_aliases_alias_normalized'), 'player_aliases', ['alias_normalized'], unique=False)
    op.create_table('player_stats_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'as_of', name='uq_stats_cache')
    )
    op.create_table('advisories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_ticker', sa.String(length=96), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.Column('recommended_player_id', sa.BigInteger(), nullable=True),
    sa.Column('model_prob', sa.Float(), nullable=False),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('executable_price_cents', sa.Integer(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('market_volume', sa.Integer(), nullable=True),
    sa.Column('inferred_state', sa.String(length=16), nullable=True),
    sa.Column('state_confidence', sa.Float(), nullable=True),
    sa.Column('state_confirmed', sa.Boolean(), nullable=False),
    sa.Column('probation', sa.Boolean(), nullable=False),
    sa.Column('fact_block', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prose', sa.Text(), nullable=True),
    sa.Column('validator_passed', sa.Boolean(), nullable=True),
    sa.Column('used_template_fallback', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('kill_reason', sa.String(length=64), nullable=True),
    sa.Column('discord_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['recommended_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_market_ticker'), 'advisories', ['market_ticker'], unique=False)
    op.create_table('kalshi_markets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=96), nullable=False),
    sa.Column('event_ticker', sa.String(length=96), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('player_a_id', sa.BigInteger(), nullable=True),
    sa.Column('player_b_id', sa.BigInteger(), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_a_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('live_match_state',
    sa.Column('market_ticker', sa.String(length=96), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_confirmed_state', sa.String(length=16), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('market_ticker')
    )
    op.create_table('match_sets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('winner_games', sa.Integer(), nullable=False),
    sa.Column('loser_games', sa.Integer(), nullable=False),
    sa.Column('set_won_by_match_winner', sa.Boolean(), nullable=False),
    sa.Column('tiebreak', sa.Boolean(), nullable=False),
    sa.Column('tiebreak_loser_points', sa.Integer(), nullable=True),
    sa.Column('is_match_tiebreak', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'set_number', name='uq_match_sets')
    )
    op.create_index(op.f('ix_match_sets_match_id'), 'match_sets', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_sets_match_id'), table_name='match_sets')
    op.drop_table('match_sets')
    op.drop_table('live_match_state')
    op.drop_table('kalshi_markets')
    op.drop_index(op.f('ix_advisories_market_ticker'), table_name='advisories')
    op.drop_table('advisories')
    op.drop_table('player_stats_cache')
    op.drop_index(op.f('ix_player_aliases_alias_normalized'), table_name='player_aliases')
    op.drop_table('player_aliases')
    op.drop_index('ix_matches_winner_date', table_name='matches')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index('ix_matches_loser_date', table_name='matches')
    op.drop_table('matches')
    op.drop_table('match_review_queue')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_state_inference_log_session_id'), table_name='state_inference_log')
    op.drop_index(op.f('ix_state_inference_log_market_ticker'), table_name='state_inference_log')
    op.drop_table('state_inference_log')
    op.drop_index(op.f('ix_players_normalized_name'), table_name='players')
    op.drop_index('ix_players_api_tennis', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_ticks_market_ts', table_name='market_ticks')
    op.drop_index(op.f('ix_market_ticks_session_id'), table_name='market_ticks')
    op.drop_table('market_ticks')
    op.drop_table('ingest_state')
    op.drop_index(op.f('ix_feed_gaps_market_ticker'), table_name='feed_gaps')
    op.drop_table('feed_gaps')
    # ### end Alembic commands ###
