"""charting_stats table

Revision ID: c842dfb036d9
Revises: 5b6d508ce8e6
Create Date: 2026-07-20 00:07:54.280956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c842dfb036d9'
down_revision: Union[str, None] = '5b6d508ce8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charting_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=160), nullable=False),
    sa.Column('tour', sa.String(length=8), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('player_name', sa.String(length=160), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('tournament', sa.String(length=128), nullable=True),
    sa.Column('surface', sa.String(length=16), nullable=True),
    sa.Column('serve_pts', sa.Integer(), nullable=True),
    sa.Column('aces', sa.Integer(), nullable=True),
    sa.Column('dfs', sa.Integer(), nullable=True),
    sa.Column('first_in', sa.Integer(), nullable=True),
    sa.Column('first_won', sa.Integer(), nullable=True),
    sa.Column('second_in', sa.Integer(), nullable=True),
    sa.Column('second_won', sa.Integer(), nullable=True),
    sa.Column('bk_pts', sa.Integer(), nullable=True),
    sa.Column('bp_saved', sa.Integer(), nullable=True),
    sa.Column('return_pts', sa.Integer(), nullable=True),
    sa.Column('return_pts_won', sa.Integer(), nullable=True),
    sa.Column('winners', sa.Integer(), nullable=True),
    sa.Column('winners_fh', sa.Integer(), nullable=True),
    sa.Column('winners_bh', sa.Integer(), nullable=True),
    sa.Column('unforced', sa.Integer(), nullable=True),
    sa.Column('unforced_fh', sa.Integer(), nullable=True),
    sa.Column('unforced_bh', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_name', name='uq_charting_match_player')
    )
    op.create_index('ix_charting_player', 'charting_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_charting_player', table_name='charting_stats')
    op.drop_table('charting_stats')
    # ### end Alembic commands ###
