"""paper_bets table

Revision ID: c8e785f1e415
Revises: d43d28cebde6
Create Date: 2026-07-19 23:18:15.598811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c8e785f1e415'
down_revision: Union[str, None] = 'd43d28cebde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_bets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_ticker', sa.String(length=96), nullable=False),
    sa.Column('market_ticker', sa.String(length=96), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('model_prob', sa.Float(), nullable=False),
    sa.Column('model_confidence', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('basis', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.String(length=8), nullable=True),
    sa.Column('state_at_placement', sa.String(length=16), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pnl_cents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_bets')
    # ### end Alembic commands ###
