"""scenarios table

Revision ID: d43d28cebde6
Revises: 6b5787a61ff4
Create Date: 2026-07-19 22:28:29.755417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd43d28cebde6'
down_revision: Union[str, None] = '6b5787a61ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_for', sa.Date(), nullable=False),
    sa.Column('event_ticker', sa.String(length=96), nullable=False),
    sa.Column('market_ticker', sa.String(length=96), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('opponent_id', sa.BigInteger(), nullable=True),
    sa.Column('scenario_state', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('model_prob_at_state', sa.Float(), nullable=False),
    sa.Column('prematch_prob', sa.Float(), nullable=False),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opponent_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_for', 'market_ticker', 'scenario_state', 'kind', name='uq_scenarios_day')
    )
    op.create_index(op.f('ix_scenarios_created_for'), 'scenarios', ['created_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_created_for'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
