"""Daily gameflow scenarios — pre-match, state-conditional situations worth
watching for. Generated by the daily cron for matches in the next 48h.

Two scenario kinds (v1):

- decider_edge: the deciding-set records of the two players diverge enough
  that reaching a decider makes one side notably live. The core differentiator
  of this bot, computed pre-match.
- resilient_favorite: a strong model favorite whose conditional win prob while
  DOWN a set stays near/above the market's likely panic price — "don't fade
  the favorite on one set" (or: value appears if the market overreacts).

All numbers come from the stats/probability engines — narrative text is built
from the same fact values (no generation, no fabrication). Advisory-only.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from bot.log import get_logger
from bot.models import KalshiMarket, Scenario
from bot.prob.elo import SetElo
from bot.prob.model import MatchState
from bot.prob.state_adjust import condition_on_state

log = get_logger("scenarios")

HORIZON_H = 48
TOP_N = 40
MIN_DECIDER_DIFF = 0.12
MIN_DECIDER_SAMPLE = 4
RESILIENT_MIN_PREMATCH = 0.65
RESILIENT_MAX_PREMATCH = 0.90  # above this it's a blowout — market won't move enough
RESILIENT_MIN_DOWN = 0.40  # model prob while down a set; market panic zone is lower
MAX_RESILIENT_KEPT = 15  # decider edges are the differentiator; don't crowd them out
SERIES_TIER = {"KXATPMATCH": "A", "KXWTAMATCH": "A", "KXWTAGAME": "A",
               "KXATPCHALLENGERMATCH": "C"}


@dataclass
class Candidate:
    market_ticker: str
    event_ticker: str
    player_id: int
    opponent_id: int
    state_key: str
    kind: str
    p_at_state: float
    p_prematch: float
    salience: float
    narrative: str
    facts: dict
    scheduled_start: datetime | None


def decider_label(best_of: int) -> str:
    return f"set {best_of}"


def build_candidates_for_match(*, ticker_a: str, ticker_b: str, event_ticker: str,
                               name_a: str, name_b: str, id_a: int, id_b: int,
                               prof_a, prof_b, p_a: float, best_of: int,
                               start: datetime | None,
                               event_label: str = "") -> list[Candidate]:
    """Pure scenario logic — testable without DB. p_a = prematch P(A wins)."""
    out: list[Candidate] = []
    need = best_of // 2 + 1
    dec_state = MatchState(need - 1, need - 1, best_of)
    lab = decider_label(best_of)
    sur_a, sur_b = name_a.split()[-1], name_b.split()[-1]

    # --- decider_edge ---
    da, db_ = prof_a.deciding.best, prof_b.deciding.best
    if (da.value is not None and db_.value is not None
            and min(da.n, db_.n) >= MIN_DECIDER_SAMPLE):
        diff = da.value - db_.value
        if abs(diff) >= MIN_DECIDER_DIFF:
            # perspective of the better decider player
            if diff > 0:
                tick, pid, oid, nm, opp = ticker_a, id_a, id_b, sur_a, sur_b
                dgood, dbad, p_dec = da, db_, condition_on_state(p_a, dec_state)
            else:
                tick, pid, oid, nm, opp = ticker_b, id_b, id_a, sur_b, sur_a
                dgood, dbad, p_dec = db_, da, condition_on_state(1 - p_a, dec_state)
            bits = [f"If this reaches {lab}: {nm} is {dgood.wins}-{dgood.losses} in "
                    f"{lab}s, {opp} is {dbad.wins}-{dbad.losses} — a "
                    f"{int(round(abs(diff) * 100))}% decider gap."]
            st_b = prof_b.deciding if diff > 0 else prof_a.deciding
            if st_b.streak <= -3:
                bits.append(f"{opp} has lost {abs(st_b.streak)} straight {lab}s.")
            sk = st_b.skunk_share_of_wins_365
            if not sk.is_omitted and sk.value is not None and sk.value >= 0.8 and sk.n >= 5:
                bits.append(f"{int(round(sk.value * 100))}% of {opp}'s last-year wins "
                            f"were straight-sets — untested in {lab}s.")
            bits.append(f"Model has {nm} at {p_dec:.0%} once the decider starts.")
            sal = abs(diff) * min(1.0, min(da.n, db_.n) / 10) \
                + (0.15 if st_b.streak <= -3 else 0)
            out.append(Candidate(
                market_ticker=tick, event_ticker=event_ticker, player_id=pid,
                opponent_id=oid, state_key=dec_state.key, kind="decider_edge",
                p_at_state=round(p_dec, 3), p_prematch=round(p_a if diff > 0 else 1 - p_a, 3),
                salience=round(sal, 3), narrative=" ".join(bits),
                facts={"decider_a": [dgood.wins, dgood.losses],
                       "decider_b": [dbad.wins, dbad.losses],
                       "diff": round(diff, 3), "match": f"{name_a} vs {name_b}",
                       "event_label": event_label},
                scheduled_start=start))

    # --- resilient_favorite ---
    for p, tick, pid, oid, nm in ((p_a, ticker_a, id_a, id_b, sur_a),
                                  (1 - p_a, ticker_b, id_b, id_a, sur_b)):
        if not (RESILIENT_MIN_PREMATCH <= p <= RESILIENT_MAX_PREMATCH):
            continue
        down = MatchState(0, 1, best_of)
        p_down = condition_on_state(p, down)
        if p_down >= RESILIENT_MIN_DOWN:
            out.append(Candidate(
                market_ticker=tick, event_ticker=event_ticker, player_id=pid,
                opponent_id=oid, state_key=down.key, kind="resilient_favorite",
                p_at_state=round(p_down, 3), p_prematch=round(p, 3),
                salience=round((p - RESILIENT_MIN_PREMATCH) * 2
                               + (p_down - RESILIENT_MIN_DOWN), 3),
                narrative=(f"{nm} opens a {p:.0%} model favorite. Even down a set, "
                           f"the model still makes it {p_down:.0%} — if the market "
                           f"panics past that after a lost first set, that gap is "
                           f"the opportunity."),
                facts={"prematch": round(p, 3), "down_a_set": round(p_down, 3),
                       "match": f"{name_a} vs {name_b}", "event_label": event_label},
                scheduled_start=start))
    return out


def generate_scenarios(db: Session, for_day: date | None = None) -> int:
    from bot.stats.profile import build_profile

    for_day = for_day or datetime.now(timezone.utc).date()
    now = datetime.now(timezone.utc)
    horizon = now + timedelta(hours=HORIZON_H)

    markets = db.execute(select(KalshiMarket).where(
        KalshiMarket.status.in_(["active", "open"]),
        KalshiMarket.player_a_id.is_not(None))).scalars().all()
    events: dict[str, list[KalshiMarket]] = {}
    for m in markets:
        occ_raw = (m.raw or {}).get("occurrence_datetime")
        if not occ_raw:
            continue
        try:
            occ = datetime.fromisoformat(occ_raw.replace("Z", "+00:00"))
        except ValueError:
            continue
        if now - timedelta(hours=6) <= occ <= horizon:
            m._occ = occ  # transient
            events.setdefault(m.event_ticker, []).append(m)

    log.info("fitting model for scenario generation")
    model = SetElo()
    model.fit_from_db(db)

    as_of = for_day + timedelta(days=1)
    candidates: list[Candidate] = []
    profiles: dict[int, object] = {}

    def prof(pid: int):
        if pid not in profiles:
            profiles[pid] = build_profile(db, pid, as_of)
        return profiles[pid]

    for ev_ticker, sides in events.items():
        if len(sides) != 2:
            continue
        a, b = sorted(sides, key=lambda m: m.ticker)
        raw = a.raw or {}
        best_of = int(raw.get("_best_of", 3))
        tier = SERIES_TIER.get(raw.get("_series", ""), "15")
        pred = model.predict(a.player_a_id, b.player_a_id, None, tier,
                             MatchState(0, 0, best_of))
        if pred.confidence < 0.3:
            continue  # not enough data on one side to say anything responsible
        try:
            candidates.extend(build_candidates_for_match(
                ticker_a=a.ticker, ticker_b=b.ticker, event_ticker=ev_ticker,
                name_a=(a.raw or {}).get("yes_sub_title", "A"),
                name_b=(b.raw or {}).get("yes_sub_title", "B"),
                id_a=a.player_a_id, id_b=b.player_a_id,
                prof_a=prof(a.player_a_id), prof_b=prof(b.player_a_id),
                p_a=pred.p_a, best_of=best_of, start=getattr(a, "_occ", None),
                event_label=(a.title or "").split(":")[0].replace("Will ", "")))
        except Exception as e:
            log.warning("scenario build failed", event=ev_ticker, error=str(e))

    candidates.sort(key=lambda c: c.salience, reverse=True)
    keep, n_resilient = [], 0
    for c in candidates:
        if c.kind == "resilient_favorite":
            if n_resilient >= MAX_RESILIENT_KEPT:
                continue
            n_resilient += 1
        keep.append(c)
        if len(keep) >= TOP_N:
            break
    db.execute(delete(Scenario).where(Scenario.created_for == for_day))
    for c in keep:
        db.add(Scenario(created_for=for_day, event_ticker=c.event_ticker,
                        market_ticker=c.market_ticker, player_id=c.player_id,
                        opponent_id=c.opponent_id, scenario_state=c.state_key,
                        kind=c.kind, model_prob_at_state=c.p_at_state,
                        prematch_prob=c.p_prematch, salience=c.salience,
                        narrative=c.narrative, facts=c.facts,
                        scheduled_start=c.scheduled_start,
                        created_at=datetime.now(timezone.utc)))
    db.commit()
    log.info("scenarios generated", day=str(for_day), candidates=len(candidates),
             kept=len(keep))
    return len(keep)
