"""Daily gameflow scenarios — a sequenced in-play plan per upcoming match.

Modeled on how a sharp actually talks through a match: which side is the play,
what the first entry trigger is, why set 2 is leverage, what the decider looks
like, whether fatigue is live, and when to stay away. Every number comes from
the stats/probability engines (per-set-number win rates, decider records,
conditional probabilities, yesterday's schedule) — the entry *triggers* ("up
two games") are fixed strategy conventions, not statistics.

Generated by the daily cron for matches in the next 48h. Advisory-only.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from bot.advisory.facts import build_facts
from bot.log import get_logger
from bot.models import KalshiMarket, Scenario
from bot.prob.elo import SetElo
from bot.prob.model import MatchState
from bot.prob.state_adjust import condition_on_state

log = get_logger("scenarios")

HORIZON_H = 48
TOP_N = 30
MIN_SET_RATE_GAP = 0.08  # set-1 edge worth calling out
SWEET_LO, SWEET_HI = 0.50, 0.85  # model-prob band where markets actually move
SERIES_TIER = {"KXATPMATCH": "A", "KXWTAMATCH": "A", "KXWTAGAME": "A",
               "KXATPCHALLENGERMATCH": "C"}


@dataclass
class Candidate:
    market_ticker: str
    event_ticker: str
    player_id: int
    opponent_id: int
    state_key: str
    kind: str
    p_at_state: float
    p_prematch: float
    salience: float
    narrative: str
    facts: dict
    scheduled_start: datetime | None


def decider_label(best_of: int) -> str:
    return f"set {best_of}"


def _pct(stat) -> int | None:
    return int(round(stat.value * 100)) if stat and stat.value is not None else None


def _wp(window: str) -> str:
    if "last365" in window:
        return "past year"
    if "career" in window:
        return "career"
    return "recent"


def _rate_n(stat) -> str | None:
    """'68% (34-16, past year)' — every cited rate carries its sample."""
    if stat is None or stat.value is None:
        return None
    return f"{int(round(stat.value * 100))}% ({stat.wins}-{stat.losses}, {_wp(stat.window)})"


def _supporting_analysis(prof_watch, prof_opp, hist_watch, hist_opp,
                         state: MatchState, as_of: date,
                         exclude_prefixes: tuple = ()) -> tuple[str, list[dict]]:
    """Extra depth from the advisory fact engine (form, H2H, common opponents,
    trajectory, streaks) — salience-ranked, deterministic."""
    facts = build_facts(prof_watch, prof_opp, hist_watch, hist_opp, state,
                        as_of, max_facts=9)
    picked = [f for f in facts
              if not any(f.key.startswith(p) for p in exclude_prefixes)][:4]
    text = " ".join(f.sentence_hint + "." for f in picked)
    payload = [{"key": f.key, "data": f.data} for f in picked]
    return text, payload


def build_gameflow(*, ticker_a: str, ticker_b: str, event_ticker: str,
                   name_a: str, name_b: str, id_a: int, id_b: int,
                   prof_a, prof_b, hist_a, hist_b,
                   set_rates_a: dict, set_rates_b: dict,
                   p_a: float, best_of: int, start: datetime | None, as_of: date,
                   model_confidence: float = 1.0,
                   fatigue_a: dict | None = None,
                   fatigue_b: dict | None = None,
                   event_label: str = "") -> Candidate | None:
    """One sequenced gameflow plan for the match, from the watch side's view.

    Pure logic — testable without a DB.
    """
    lab = decider_label(best_of)
    need = best_of // 2 + 1
    dec_state = MatchState(need - 1, need - 1, best_of)

    # pick the watch side: model lean + set-1 edge + decider edge
    def val(stat):
        return stat.value if stat and stat.value is not None else None

    s1a, s1b = val(set_rates_a.get(1)), val(set_rates_b.get(1))
    da, db_ = prof_a.deciding.best, prof_b.deciding.best
    score_a = (p_a - 0.5)
    if s1a is not None and s1b is not None:
        score_a += 0.5 * (s1a - s1b)
    if da.value is not None and db_.value is not None:
        score_a += 0.4 * (da.value - db_.value)
    if score_a >= 0:
        w_tick, w_id, o_id = ticker_a, id_a, id_b
        w_prof, o_prof, w_hist, o_hist = prof_a, prof_b, hist_a, hist_b
        w_rates, o_rates = set_rates_a, set_rates_b
        w_name, o_name = name_a.split()[-1], name_b.split()[-1]
        p_w = p_a
        w_fat, o_fat = fatigue_a, fatigue_b
    else:
        w_tick, w_id, o_id = ticker_b, id_b, id_a
        w_prof, o_prof, w_hist, o_hist = prof_b, prof_a, hist_b, hist_a
        w_rates, o_rates = set_rates_b, set_rates_a
        w_name, o_name = name_b.split()[-1], name_a.split()[-1]
        p_w = 1 - p_a
        w_fat, o_fat = fatigue_b, fatigue_a

    p_dec = condition_on_state(p_w, dec_state)
    bits: list[str] = []
    salience = 0.0

    # 1. entry thesis: set-1 strength (rates always cited with their samples)
    s1w, s1o = _pct(w_rates.get(1)), _pct(o_rates.get(1))
    w_all = {n: _pct(s) for n, s in w_rates.items() if _pct(s) is not None}
    if s1w is not None and s1o is not None and s1w - s1o >= MIN_SET_RATE_GAP * 100:
        strongest = (max(w_all, key=w_all.get) == 1) if w_all else False
        bits.append(f"{w_name} is the play. Set 1 is "
                    f"{'their strongest set — ' if strongest else 'the opening edge: '}"
                    f"{_rate_n(w_rates.get(1))} vs {_rate_n(o_rates.get(1))} for "
                    f"{o_name}. First entry: {w_name} up two games early in set 1 "
                    f"— that break is the signal.")
        salience += (s1w - s1o) / 100 * 0.8
    else:
        bits.append(f"{w_name} is the play at {p_w:.0%} on the model.")

    # 2. set-2 leverage
    s2o = _pct(o_rates.get(2))
    o_all = {n: _pct(s) for n, s in o_rates.items() if _pct(s) is not None}
    if s2o is not None and o_all and min(o_all, key=o_all.get) == 2 and s2o <= 45:
        bits.append(f"If {w_name} takes set 1, it gets steep for {o_name}: set 2 "
                    f"is {o_name}'s weakest set at {_rate_n(o_rates.get(2))} — "
                    f"forcing a {lab} is an uphill battle.")
        salience += (45 - s2o) / 100 * 0.6
    else:
        s2w = _pct(w_rates.get(2))
        if s2w is not None and s2w >= 55:
            bits.append(f"{w_name} closes well — {_rate_n(w_rates.get(2))} in set 2s.")
            salience += 0.05

    # 2b. conditional-on-set-1 gameflow ("takes set 1 → over" / "drops it → don't panic")
    cond = getattr(w_prof, "conditional", None)
    if cond:
        g1 = cond.win_given_set1_won
        if not g1.is_omitted and g1.value is not None and g1.value >= 0.80:
            bits.append(f"If {w_name} takes set 1, it's usually over: "
                        f"{g1.wins}-{g1.losses} ({int(round(g1.value * 100))}%) in "
                        f"matches after winning the opener — expect the price to run.")
            salience += (g1.value - 0.80) * 0.6
        dl = cond.decider_given_set1_lost
        gl = cond.win_given_set1_lost
        if not dl.is_omitted and dl.value is not None and dl.value >= 0.55:
            recover = ""
            if not gl.is_omitted and gl.value is not None:
                recover = (f", and still wins {int(round(gl.value * 100))}% "
                           f"of the time from a set down")
            bits.append(f"Don't panic if {w_name} drops set 1 — they force a {lab} "
                        f"{int(round(dl.value * 100))}% of the time after losing the "
                        f"opener{recover}.")
            salience += 0.1

    # 3. decider branch
    dw = do = None
    if da.value is not None and db_.value is not None:
        dw, do = (da, db_) if w_tick == ticker_a else (db_, da)
        recs = (f"{w_name} is {dw.wins}-{dw.losses} in {lab}s ({_wp(dw.window)}) "
                f"against {o_name}'s {do.wins}-{do.losses} ({_wp(do.window)})")
        if dw.value >= do.value + 0.05:
            bits.append(f"If it reaches {lab}: {recs} — the distance favors "
                        f"{w_name}, and the model makes it {p_dec:.0%} once the "
                        f"decider starts.")
        elif dw.value <= do.value - 0.05:
            bits.append(f"The caveat: {recs}, so the edge thins if this goes the "
                        f"distance — the model still reads {p_dec:.0%} in a "
                        f"decider on overall strength, but consider taking profit "
                        f"before {lab} rather than sweating it.")
        else:
            bits.append(f"Deciders are close to a coin flip on record ({recs}); "
                        f"model reads {p_dec:.0%} there.")
        salience += abs(dw.value - do.value) * 0.8
        o_dec = o_prof.deciding
        if o_dec.streak <= -3:
            bits.append(f"{o_name} has lost {abs(o_dec.streak)} straight {lab}s.")
            salience += 0.1

    # 4. fatigue
    if o_fat and o_fat.get("played"):
        dist = " and went the distance" if o_fat.get("went_distance") else ""
        bits.append(f"{o_name} played yesterday{dist} — fatigue is live in the "
                    f"later sets.")
        salience += 0.15 if o_fat.get("went_distance") else 0.08
    if w_fat and w_fat.get("played") and w_fat.get("went_distance"):
        bits.append(f"(Caveat: {w_name} also went the distance yesterday.)")
        salience -= 0.05

    # 5. risk rule — strategy convention, not a statistic
    bits.append(f"If {w_name} drops set 1, do not chase: the second entry only "
                f"comes if set 2 builds a clear cushion — up three games — "
                f"otherwise stay away.")

    # 6. model read with confidence — always the closing line before support
    conf_note = ""
    if model_confidence < 0.6:
        conf_note = (" — limited history on at least one side, size accordingly")
    bits.append(f"Model read: {w_name} {p_w:.0%} prematch, {p_dec:.0%} in a "
                f"decider (model confidence {model_confidence:.0%}{conf_note}).")

    # 7. supporting depth (form / H2H / common opponents / trajectory)
    support_text, support = _supporting_analysis(
        w_prof, o_prof, w_hist, o_hist, dec_state, as_of,
        exclude_prefixes=("decider_record", "decider_differential",
                          "decider_streak", "skunk_share"))
    if support_text:
        bits.append(support_text)

    if SWEET_LO <= p_w <= SWEET_HI:
        salience += 0.15  # market can actually move through this range

    return Candidate(
        market_ticker=w_tick, event_ticker=event_ticker, player_id=w_id,
        opponent_id=o_id, state_key="plan", kind="gameflow",
        p_at_state=round(p_dec, 3), p_prematch=round(p_w, 3),
        salience=round(salience, 3), narrative=" ".join(bits),
        facts={
            "match": f"{name_a} vs {name_b}", "event_label": event_label,
            "set_rates_watch": {n: _pct(s) for n, s in w_rates.items()},
            "set_rates_opp": {n: _pct(s) for n, s in o_rates.items()},
            "decider_watch": [dw.wins, dw.losses] if dw is not None else None,
            "decider_opp": [do.wins, do.losses] if do is not None else None,
            "fatigue_opp": o_fat, "support": support,
            "model_confidence": round(model_confidence, 2),
        },
        scheduled_start=start)


def _yesterday_played(db: Session, now: datetime) -> dict[int, dict]:
    """player_id -> fatigue flags from yesterday's Kalshi schedule."""
    lo, hi = now - timedelta(hours=40), now - timedelta(hours=8)
    out: dict[int, dict] = {}
    for m in db.execute(select(KalshiMarket).where(
            KalshiMarket.player_a_id.is_not(None))).scalars().all():
        occ_raw = (m.raw or {}).get("occurrence_datetime")
        if not occ_raw:
            continue
        try:
            occ = datetime.fromisoformat(occ_raw.replace("Z", "+00:00"))
        except ValueError:
            continue
        if lo <= occ <= hi:
            went = None
            fs = (m.raw or {}).get("_final_sets")
            if fs is not None:
                went = int(fs) >= int((m.raw or {}).get("_best_of", 3))
            prev = out.get(m.player_a_id)
            out[m.player_a_id] = {
                "played": True,
                "went_distance": bool(went) or bool(prev and prev.get("went_distance")),
            }
    return out


def generate_scenarios(db: Session, for_day: date | None = None) -> int:
    from bot.stats.profile import build_profile, compute_set_rates, load_history

    for_day = for_day or datetime.now(timezone.utc).date()
    now = datetime.now(timezone.utc)
    horizon = now + timedelta(hours=HORIZON_H)

    markets = db.execute(select(KalshiMarket).where(
        KalshiMarket.status.in_(["active", "open"]),
        KalshiMarket.player_a_id.is_not(None))).scalars().all()
    events: dict[str, list[KalshiMarket]] = {}
    occs: dict[str, datetime] = {}
    for m in markets:
        occ_raw = (m.raw or {}).get("occurrence_datetime")
        if not occ_raw:
            continue
        try:
            occ = datetime.fromisoformat(occ_raw.replace("Z", "+00:00"))
        except ValueError:
            continue
        if now - timedelta(hours=6) <= occ <= horizon:
            events.setdefault(m.event_ticker, []).append(m)
            occs[m.event_ticker] = occ

    log.info("fitting model for scenario generation")
    model = SetElo()
    model.fit_from_db(db)
    fatigue = _yesterday_played(db, now)

    as_of = for_day + timedelta(days=1)
    candidates: list[Candidate] = []
    cache: dict[int, tuple] = {}

    def pdata(pid: int):
        if pid not in cache:
            hist = load_history(db, pid)
            cache[pid] = (build_profile(db, pid, as_of), hist,
                          compute_set_rates(hist, as_of))
        return cache[pid]

    for ev_ticker, sides in events.items():
        if len(sides) != 2:
            continue
        a, b = sorted(sides, key=lambda m: m.ticker)
        raw = a.raw or {}
        best_of = int(raw.get("_best_of", 3))
        tier = SERIES_TIER.get(raw.get("_series", ""), "15")
        pred = model.predict(a.player_a_id, b.player_a_id, None, tier,
                             MatchState(0, 0, best_of))
        if pred.confidence < 0.3:
            continue  # not enough data to say anything responsible
        try:
            prof_a, hist_a, rates_a = pdata(a.player_a_id)
            prof_b, hist_b, rates_b = pdata(b.player_a_id)
            cand = build_gameflow(
                ticker_a=a.ticker, ticker_b=b.ticker, event_ticker=ev_ticker,
                name_a=(a.raw or {}).get("yes_sub_title", "A"),
                name_b=(b.raw or {}).get("yes_sub_title", "B"),
                id_a=a.player_a_id, id_b=b.player_a_id,
                prof_a=prof_a, prof_b=prof_b, hist_a=hist_a, hist_b=hist_b,
                set_rates_a=rates_a, set_rates_b=rates_b,
                p_a=pred.p_a, best_of=best_of, start=occs.get(ev_ticker),
                as_of=as_of, model_confidence=pred.confidence,
                fatigue_a=fatigue.get(a.player_a_id),
                fatigue_b=fatigue.get(b.player_a_id),
                event_label=(a.title or "").split(":")[0].replace("Will ", ""))
            if cand is not None:
                candidates.append(cand)
        except Exception as e:
            log.warning("scenario build failed", event=ev_ticker, error=str(e))

    candidates.sort(key=lambda c: c.salience, reverse=True)
    keep = candidates[:TOP_N]
    db.execute(delete(Scenario).where(Scenario.created_for == for_day))
    for c in keep:
        db.add(Scenario(created_for=for_day, event_ticker=c.event_ticker,
                        market_ticker=c.market_ticker, player_id=c.player_id,
                        opponent_id=c.opponent_id, scenario_state=c.state_key,
                        kind=c.kind, model_prob_at_state=c.p_at_state,
                        prematch_prob=c.p_prematch, salience=c.salience,
                        narrative=c.narrative, facts=c.facts,
                        scheduled_start=c.scheduled_start,
                        created_at=datetime.now(timezone.utc)))
    db.commit()
    log.info("scenarios generated", day=str(for_day), candidates=len(candidates),
             kept=len(keep))
    return len(keep)
