"""Daily gameflow scenarios — a sequenced in-play plan per upcoming match.

Modeled on how a sharp actually talks through a match: which side is the play,
what the first entry trigger is, why set 2 is leverage, what the decider looks
like, whether fatigue is live, and when to stay away. Every number comes from
the stats/probability engines (per-set-number win rates, decider records,
conditional probabilities, yesterday's schedule) — the entry *triggers* ("up
two games") are fixed strategy conventions, not statistics.

Generated by the daily cron for matches in the next 48h. Advisory-only.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from bot.advisory.facts import build_facts
from bot.log import get_logger
from bot.models import KalshiMarket, Scenario
from bot.prob.elo import SetElo
from bot.prob.model import MatchState
from bot.prob.state_adjust import condition_on_state

log = get_logger("scenarios")

HORIZON_H = 48
TOP_N = 500  # keep analysis for every analyzable match (the compute already
# happens for all; this only bounds storage). Salience still ranks them, so the
# /scenarios BEST flag and the live board surface the strongest.
MIN_SET_RATE_GAP = 0.08  # set-1 edge worth calling out
THIN_SAMPLE = 10  # a rate on fewer decisions than this is an early read, not a trend
SWEET_LO, SWEET_HI = 0.50, 0.85  # model-prob band where markets actually move
SERIES_TIER = {"KXATPMATCH": "A", "KXWTAMATCH": "A", "KXWTAGAME": "A",
               "KXATPCHALLENGERMATCH": "C"}


@dataclass
class Candidate:
    market_ticker: str
    event_ticker: str
    player_id: int
    opponent_id: int
    state_key: str
    kind: str
    p_at_state: float
    p_prematch: float
    salience: float
    narrative: str
    facts: dict
    scheduled_start: datetime | None


def decider_label(best_of: int) -> str:
    return f"set {best_of}"


def _pct(stat) -> int | None:
    return int(round(stat.value * 100)) if stat and stat.value is not None else None


def _wp(window: str) -> str:
    if "last365" in window:
        return "past year"
    if "career" in window:
        return "career"
    return "recent"


def _is_thin(stat) -> bool:
    """A cited rate resting on fewer than THIN_SAMPLE decisions — honest prose
    must not read a 4-0 as if it were a 40-0 (CLAUDE.md rule 4)."""
    return stat is not None and not stat.is_omitted and (stat.n or 0) < THIN_SAMPLE


def _rate_n(stat) -> str | None:
    """'68% (34-16, past year)' — every cited rate carries its sample, and a
    thin sample (or one we had to widen off recent form) is flagged inline so
    the number is never read as more solid than it is."""
    if stat is None or stat.value is None:
        return None
    win = _wp(stat.window)
    if _is_thin(stat):
        win += ", thin sample"
    elif stat.method == "widened":
        win = "career — recent sample too thin"
    return f"{int(round(stat.value * 100))}% ({stat.wins}-{stat.losses}, {win})"


def _supporting_analysis(prof_watch, prof_opp, hist_watch, hist_opp,
                         state: MatchState, as_of: date,
                         exclude_prefixes: tuple = ()) -> tuple[str, list[dict]]:
    """Extra depth from the advisory fact engine (form, H2H, common opponents,
    trajectory, streaks) — salience-ranked, deterministic."""
    facts = build_facts(prof_watch, prof_opp, hist_watch, hist_opp, state,
                        as_of, max_facts=9)
    picked = [f for f in facts
              if not any(f.key.startswith(p) for p in exclude_prefixes)][:4]
    text = " ".join(f.sentence_hint + "." for f in picked)
    payload = [{"key": f.key, "data": f.data} for f in picked]
    return text, payload


MIN_FIELD = 30  # need this many peers before a percentile means anything


def load_tour_distributions(db: Session) -> dict:
    """Sorted per-tour distributions of set rates + win-after-a-set, read from
    the stats cache, for percentile-within-field context ('top 1% of ITF')."""
    from sqlalchemy import text as sqltext
    rows = db.execute(sqltext("""
        SELECT DISTINCT ON (c.player_id) p.tour, c.payload
        FROM player_stats_cache c JOIN players p ON p.id = c.player_id
        ORDER BY c.player_id, c.as_of DESC""")).all()
    dist: dict[str, dict[str, list]] = {}
    for tour, payload in rows:
        d = dist.setdefault(tour, {"set1": [], "set2": [], "set3": [], "won_a_set": []})
        sr = (payload or {}).get("set_rates") or {}
        for n, key in ((1, "set1"), (2, "set2"), (3, "set3")):
            s = sr.get(str(n)) or sr.get(n)
            if s and s.get("value") is not None and (s.get("n") or 0) >= 8:
                d[key].append(s["value"])
        cond = (payload or {}).get("conditional") or {}
        w = cond.get("win_given_won_a_set")
        if w and w.get("value") is not None and (w.get("n") or 0) >= 8:
            d["won_a_set"].append(w["value"])
    for t in dist:
        for k in dist[t]:
            dist[t][k].sort()
    return dist


def _pct_rank(sorted_vals: list, v) -> float | None:
    """Fraction of the field strictly below v (0..1); None if the field is too
    small to be meaningful."""
    if v is None or len(sorted_vals) < MIN_FIELD:
        return None
    import bisect
    return bisect.bisect_left(sorted_vals, v) / len(sorted_vals)


def build_gameflow(*, ticker_a: str, ticker_b: str, event_ticker: str,
                   name_a: str, name_b: str, id_a: int, id_b: int,
                   prof_a, prof_b, hist_a, hist_b,
                   set_rates_a: dict, set_rates_b: dict,
                   p_a: float, best_of: int, start: datetime | None, as_of: date,
                   model_confidence: float = 1.0,
                   fatigue_a: dict | None = None,
                   fatigue_b: dict | None = None,
                   event_label: str = "",
                   pctl: dict | None = None) -> Candidate | None:
    """One sequenced gameflow plan for the match, from the watch side's view.

    Pure logic — testable without a DB.
    """
    lab = decider_label(best_of)
    need = best_of // 2 + 1
    dec_state = MatchState(need - 1, need - 1, best_of)

    # pick the watch side: model lean + set-1 edge + decider edge
    def val(stat):
        return stat.value if stat and stat.value is not None else None

    s1a, s1b = val(set_rates_a.get(1)), val(set_rates_b.get(1))
    da, db_ = prof_a.deciding.best, prof_b.deciding.best
    score_a = (p_a - 0.5)
    if s1a is not None and s1b is not None:
        score_a += 0.5 * (s1a - s1b)
    if da.value is not None and db_.value is not None:
        score_a += 0.4 * (da.value - db_.value)
    if score_a >= 0:
        w_tick, w_id, o_id = ticker_a, id_a, id_b
        w_prof, o_prof, w_hist, o_hist = prof_a, prof_b, hist_a, hist_b
        w_rates, o_rates = set_rates_a, set_rates_b
        w_name, o_name = name_a.split()[-1], name_b.split()[-1]
        p_w = p_a
        w_fat, o_fat = fatigue_a, fatigue_b
    else:
        w_tick, w_id, o_id = ticker_b, id_b, id_a
        w_prof, o_prof, w_hist, o_hist = prof_b, prof_a, hist_b, hist_a
        w_rates, o_rates = set_rates_b, set_rates_a
        w_name, o_name = name_b.split()[-1], name_a.split()[-1]
        p_w = 1 - p_a
        w_fat, o_fat = fatigue_b, fatigue_a

    p_dec = condition_on_state(p_w, dec_state)
    bits: list[str] = []
    salience = 0.0

    # 1. entry thesis: set-1 strength (rates always cited with their samples)
    s1w, s1o = _pct(w_rates.get(1)), _pct(o_rates.get(1))
    w_all = {n: _pct(s) for n, s in w_rates.items() if _pct(s) is not None}
    if s1w is not None and s1o is not None and s1w - s1o >= MIN_SET_RATE_GAP * 100:
        # only crown a "strongest set" on a sample solid enough to mean it
        strongest = (max(w_all, key=w_all.get) == 1
                     and not _is_thin(w_rates.get(1))) if w_all else False
        bits.append(f"{w_name} is the play. Set 1 is "
                    f"{'their strongest set — ' if strongest else 'the opening edge: '}"
                    f"{_rate_n(w_rates.get(1))} vs {_rate_n(o_rates.get(1))} for "
                    f"{o_name}. First entry: {w_name} up two games early in set 1 "
                    f"— that break is the signal.")
        salience += (s1w - s1o) / 100 * 0.8
    else:
        bits.append(f"{w_name} is the play at {p_w:.0%} on the model.")

    # 1b. percentile within the field — "86% set-2 win rate, top 1% of the field"
    if pctl:
        best_rank = None  # (rank, set_number, stat)
        for n, key in ((1, "set1"), (2, "set2"), (3, "set3")):
            s = w_rates.get(n)
            if s and s.value is not None and not _is_thin(s):
                r = _pct_rank(pctl.get(key, []), s.value)
                if r is not None and (best_rank is None or r > best_rank[0]):
                    best_rank = (r, n, s)
        if best_rank and best_rank[0] >= 0.85:
            r, n, s = best_rank
            top = max(1, round((1 - r) * 100))
            bits.append(f"{w_name}'s set {n} win rate ({int(round(s.value * 100))}%) "
                        f"is elite — top {top}% of the field.")
            salience += (r - 0.85) * 0.6
        # opponent weakness the same way (bottom of the field)
        for n, key in ((3, "set3"), (2, "set2"), (1, "set1")):
            s = o_rates.get(n)
            if s and s.value is not None and not _is_thin(s):
                r = _pct_rank(pctl.get(key, []), s.value)
                if r is not None and r <= 0.15:
                    bits.append(f"{o_name}'s set {n} ({int(round(s.value * 100))}%) is "
                                f"bottom {max(1, round(r * 100))}% of the field.")
                    salience += (0.15 - r) * 0.5
                    break

    # 2. set-2 leverage
    s2o = _pct(o_rates.get(2))
    o_all = {n: _pct(s) for n, s in o_rates.items() if _pct(s) is not None}
    if s2o is not None and o_all and min(o_all, key=o_all.get) == 2 and s2o <= 45:
        bits.append(f"If {w_name} takes set 1, it gets steep for {o_name}: set 2 "
                    f"is {o_name}'s weakest set at {_rate_n(o_rates.get(2))} — "
                    f"forcing a {lab} is an uphill battle.")
        salience += (45 - s2o) / 100 * 0.6
    else:
        s2w = _pct(w_rates.get(2))
        if s2w is not None and s2w >= 55:
            bits.append(f"{w_name} closes well — {_rate_n(w_rates.get(2))} in set 2s.")
            salience += 0.05

    # 2b. conditional-on-set-1 gameflow ("takes set 1 → over" / "drops it → don't panic")
    cond = getattr(w_prof, "conditional", None)
    if cond:
        g1 = cond.win_given_set1_won
        if not g1.is_omitted and g1.value is not None and g1.value >= 0.80:
            bits.append(f"If {w_name} takes set 1, it's usually over: "
                        f"{g1.wins}-{g1.losses} ({int(round(g1.value * 100))}%) in "
                        f"matches after winning the opener — expect the price to run.")
            salience += (g1.value - 0.80) * 0.6
        dl = cond.decider_given_set1_lost
        gl = cond.win_given_set1_lost
        if not dl.is_omitted and dl.value is not None and dl.value >= 0.55:
            recover = ""
            if not gl.is_omitted and gl.value is not None:
                recover = (f", and still wins {int(round(gl.value * 100))}% "
                           f"of the time from a set down")
            bits.append(f"Don't panic if {w_name} drops set 1 — they force a {lab} "
                        f"{int(round(dl.value * 100))}% of the time after losing the "
                        f"opener{recover}.")
            salience += 0.1

    # 2c. "gets a foothold, closes" — win rate once they win any set
    wa = cond.win_given_won_a_set if cond else None
    if wa and not wa.is_omitted and wa.value is not None and wa.value >= 0.85 \
            and not _is_thin(wa):
        bits.append(f"When {w_name} wins a set, they close it out: {wa.wins}-"
                    f"{wa.losses} ({int(round(wa.value * 100))}%) in matches where "
                    f"they took at least one — steal set 1 and it's usually over.")
        salience += (wa.value - 0.85) * 0.5

    # 3. decider branch
    dw = do = None
    if da.value is not None and db_.value is not None:
        dw, do = (da, db_) if w_tick == ticker_a else (db_, da)
        recs = (f"{w_name} is {dw.wins}-{dw.losses} in {lab}s ({_wp(dw.window)}) "
                f"against {o_name}'s {do.wins}-{do.losses} ({_wp(do.window)})")
        # thin decider records are noisy — soften the directional read
        dec_thin = _is_thin(dw) or _is_thin(do)
        favors = ("leans toward" if dec_thin else "favors")
        thin_note = " (thin decider samples — read it lightly)" if dec_thin else ""
        if dw.value >= do.value + 0.05:
            bits.append(f"If it reaches {lab}: {recs} — the distance {favors} "
                        f"{w_name}{thin_note}, and the model makes it {p_dec:.0%} once "
                        f"the decider starts.")
        elif dw.value <= do.value - 0.05:
            bits.append(f"The caveat: {recs}, so the edge thins if this goes the "
                        f"distance — the model still reads {p_dec:.0%} in a "
                        f"decider on overall strength, but consider taking profit "
                        f"before {lab} rather than sweating it.")
        else:
            bits.append(f"Deciders are close to a coin flip on record ({recs}); "
                        f"model reads {p_dec:.0%} there.")
        salience += abs(dw.value - do.value) * 0.8
        o_dec = o_prof.deciding
        if o_dec.streak <= -3:
            bits.append(f"{o_name} has lost {abs(o_dec.streak)} straight {lab}s.")
            salience += 0.1
        # rust / decider inexperience — hasn't been in a decider in a while
        if o_dec.days_since_decider_played and o_dec.days_since_decider_played >= 45:
            bits.append(f"{o_name} hasn't played a {lab} in "
                        f"{o_dec.days_since_decider_played} days — rusty and "
                        f"untested if this goes long.")
            salience += 0.08

    # 3c. recent deciding-set form — "won 4 of his last 5 when it goes the distance"
    def _recent_dec(prof):
        r = (prof.deciding.last_n_results or [])[:5]
        return (sum(1 for x in r if x["won"]), len(r)) if len(r) >= 3 else None
    wrd = _recent_dec(w_prof)
    if wrd and wrd[0] >= max(3, wrd[1] - 1):
        bits.append(f"And {w_name} is battle-tested late — won {wrd[0]} of their "
                    f"last {wrd[1]} {lab}s, so no need to panic if set 1 slips.")
        salience += 0.07
    ord_ = _recent_dec(o_prof)
    if ord_ and ord_[0] <= ord_[1] - 3:
        bits.append(f"{o_name} has been losing the long ones — {ord_[0]} of their "
                    f"last {ord_[1]} {lab}s won, vulnerable if this reaches {lab}.")
        salience += 0.07

    # 3b. set-2 → set-3 recovery
    s23 = getattr(w_prof, "conditional", None)
    if s23 and not s23.set3_given_lost_set2.is_omitted \
            and s23.set3_given_lost_set2.value is not None \
            and s23.set3_given_lost_set2.value >= 0.6:
        v = s23.set3_given_lost_set2
        bits.append(f"Even if {w_name} drops set 2, they take set 3 "
                    f"{int(round(v.value * 100))}% of the time ({v.wins}-{v.losses}) "
                    f"— resilient in the decider.")
        salience += 0.06

    # 4. fatigue (same-day is heavier than yesterday)
    if o_fat and o_fat.get("played"):
        when = "earlier today" if o_fat.get("played_today") else "yesterday"
        dist = " and went the distance" if o_fat.get("went_distance") else ""
        bits.append(f"{o_name} played {when}{dist} — fatigue is live in the "
                    f"later sets.")
        salience += (0.2 if o_fat.get("played_today") else 0.1) + \
            (0.05 if o_fat.get("went_distance") else 0)
    if w_fat and w_fat.get("played_today"):
        bits.append(f"(Caveat: {w_name} also played earlier today.)")
        salience -= 0.06

    # 4b. age + decline — the '41 years old and falling off' read
    o_age = getattr(o_prof, "age", None)
    o_delta = o_prof.form.ytd_vs_career_delta
    if o_age and o_age >= 34 and o_delta is not None and o_delta <= -0.08:
        bits.append(f"{o_name} is {o_age:.0f} and fading — down "
                    f"{abs(o_delta) * 100:.0f}% from career form this year.")
        salience += 0.08

    # 4b-ii. youth vs age — stamina tilts young if it goes long
    w_age = getattr(w_prof, "age", None)
    if w_age and o_age and (o_age - w_age) >= 8:
        bits.append(f"If it goes the distance, youth helps: {w_name} at "
                    f"{w_age:.0f} to {o_name}'s {o_age:.0f} — stamina favors the "
                    f"younger player in a {lab}.")
        salience += 0.05

    # 4c. recent deciding-set load → acute fatigue late (Kalshi/api recency feed)
    o_lay = getattr(o_prof, "layoff", None)
    if o_lay and o_lay.deciders_last_3d >= 1:
        bits.append(f"{o_name} played a {lab} within the last 72h — acute fatigue "
                    f"if this one also goes long.")
        salience += 0.1
    elif o_lay and o_lay.deciders_last_30d >= 3:
        bits.append(f"A {lab} would be {o_name}'s {o_lay.deciders_last_30d}th this "
                    f"month — stamina is a real question late.")
        salience += 0.06

    # 4d. layoff / return from a break — rust cuts against the returning player
    def _layoff_note(prof, name):
        lb = getattr(prof, "layoff", None)
        if not lb:
            return None
        if lb.return_layoff_days and lb.matches_since_return is not None:
            w, l = lb.record_since_return or (0, 0)
            return (f"{name} is back from a ~{lb.return_layoff_days}-day layoff — "
                    f"just {lb.matches_since_return} match(es) in ({w}-{l}), so that "
                    f"form is a thin, rusty sample")
        if lb.days_since_last_match and lb.days_since_last_match >= 45:
            return (f"{name} hasn't played in {lb.days_since_last_match} days — "
                    f"cold and untested coming in")
        return None
    o_lnote = _layoff_note(o_prof, o_name)
    if o_lnote:
        bits.append(f"{o_lnote} — an edge for {w_name}.")
        salience += 0.08
    w_lnote = _layoff_note(w_prof, w_name)
    if w_lnote:
        bits.append(f"(Caveat: {w_lnote}.)")
        salience -= 0.05

    # 5. risk rule — strategy convention, not a statistic
    bits.append(f"If {w_name} drops set 1, do not chase: the second entry only "
                f"comes if set 2 builds a clear cushion — up three games — "
                f"otherwise stay away.")

    # 5b. strength-of-schedule caveat — weak-field form is discounted
    sched = getattr(w_prof, "schedule", None)
    if sched and sched.field == "weak" and sched.avg_opp_rank:
        bits.append(f"Temper it: {w_name}'s recent form came against a soft field "
                    f"(avg opponent rank ~{int(sched.avg_opp_rank)}), so the win "
                    f"rate flatters.")
        salience -= 0.1
    elif sched and sched.field in ("elite", "strong") and sched.avg_opp_rank:
        bits.append(f"And it's real: {w_name} has been beating a {sched.field} "
                    f"field (avg rank ~{int(sched.avg_opp_rank)}).")
        salience += 0.08

    # 5c. style matchup from charting shot data (big-server-vs-weak-returner etc.)
    from bot.stats.profile import style_matchup

    w_ch = getattr(w_prof, "_charting", None)
    o_ch = getattr(o_prof, "_charting", None)
    for note in style_matchup(w_ch, o_ch, w_name, o_name)[:1]:
        bits.append(note)
        salience += 0.1

    # 6. model read with confidence — always the closing line before support
    conf_note = ""
    if model_confidence < 0.6:
        conf_note = (" — limited history on at least one side, size accordingly")
    bits.append(f"Model read: {w_name} {p_w:.0%} prematch, {p_dec:.0%} in a "
                f"decider (model confidence {model_confidence:.0%}{conf_note}).")

    # 7. supporting depth (form / H2H / common opponents / trajectory)
    support_text, support = _supporting_analysis(
        w_prof, o_prof, w_hist, o_hist, dec_state, as_of,
        exclude_prefixes=("decider_record", "decider_differential",
                          "decider_streak", "skunk_share"))
    if support_text:
        bits.append(support_text)

    if SWEET_LO <= p_w <= SWEET_HI:
        salience += 0.15  # market can actually move through this range

    return Candidate(
        market_ticker=w_tick, event_ticker=event_ticker, player_id=w_id,
        opponent_id=o_id, state_key="plan", kind="gameflow",
        p_at_state=round(p_dec, 3), p_prematch=round(p_w, 3),
        salience=round(salience, 3), narrative=" ".join(bits),
        facts={
            "match": f"{name_a} vs {name_b}", "event_label": event_label,
            "set_rates_watch": {n: _pct(s) for n, s in w_rates.items()},
            "set_rates_opp": {n: _pct(s) for n, s in o_rates.items()},
            "decider_watch": [dw.wins, dw.losses] if dw is not None else None,
            "decider_opp": [do.wins, do.losses] if do is not None else None,
            "fatigue_opp": o_fat, "support": support,
            "model_confidence": round(model_confidence, 2),
        },
        scheduled_start=start)


def _yesterday_played(db: Session, now: datetime) -> dict[int, dict]:
    """player_id -> fatigue flags: played earlier today, or yesterday, and
    whether that match went the distance."""
    today_lo = now - timedelta(hours=8)   # earlier today (already finished-ish)
    yday_lo, yday_hi = now - timedelta(hours=40), now - timedelta(hours=8)
    out: dict[int, dict] = {}
    for m in db.execute(select(KalshiMarket).where(
            KalshiMarket.player_a_id.is_not(None))).scalars().all():
        occ_raw = (m.raw or {}).get("occurrence_datetime")
        if not occ_raw:
            continue
        try:
            occ = datetime.fromisoformat(occ_raw.replace("Z", "+00:00"))
        except ValueError:
            continue
        today = today_lo <= occ <= now
        yday = yday_lo <= occ <= yday_hi
        if not (today or yday):
            continue
        went = None
        fs = (m.raw or {}).get("_final_sets")
        if fs is not None:
            went = int(fs) >= int((m.raw or {}).get("_best_of", 3))
        prev = out.get(m.player_a_id, {})
        out[m.player_a_id] = {
            "played": True,
            "played_today": today or prev.get("played_today", False),
            "went_distance": bool(went) or prev.get("went_distance", False),
        }
    return out


def generate_scenarios(db: Session, for_day: date | None = None) -> int:
    from bot.stats.profile import build_profile, compute_set_rates, load_history

    for_day = for_day or datetime.now(timezone.utc).date()
    now = datetime.now(timezone.utc)
    horizon = now + timedelta(hours=HORIZON_H)

    markets = db.execute(select(KalshiMarket).where(
        KalshiMarket.status.in_(["active", "open"]),
        KalshiMarket.player_a_id.is_not(None))).scalars().all()
    events: dict[str, list[KalshiMarket]] = {}
    occs: dict[str, datetime] = {}
    for m in markets:
        occ_raw = (m.raw or {}).get("occurrence_datetime")
        if not occ_raw:
            continue
        try:
            occ = datetime.fromisoformat(occ_raw.replace("Z", "+00:00"))
        except ValueError:
            continue
        if now - timedelta(hours=6) <= occ <= horizon:
            events.setdefault(m.event_ticker, []).append(m)
            occs[m.event_ticker] = occ

    log.info("fitting model for scenario generation")
    model = SetElo()
    model.fit_from_db(db)
    fatigue = _yesterday_played(db, now)
    distributions = load_tour_distributions(db)  # percentile-within-field context

    as_of = for_day + timedelta(days=1)
    candidates: list[Candidate] = []
    cache: dict[int, tuple] = {}

    def pdata(pid: int):
        if pid not in cache:
            from bot.models import ChartingStat
            from bot.stats.profile import compute_charting

            hist = load_history(db, pid)
            prof = build_profile(db, pid, as_of)
            ch_cols = ("winners", "winners_fh", "winners_bh", "unforced",
                       "unforced_fh", "unforced_bh", "serve_pts", "aces",
                       "first_in", "first_won", "second_in", "second_won",
                       "return_pts", "return_pts_won")
            ch_rows = [{c: getattr(r, c) for c in ch_cols} for r in db.execute(
                select(ChartingStat).where(ChartingStat.player_id == pid)).scalars()]
            prof._charting = compute_charting(ch_rows)  # for style_matchup
            cache[pid] = (prof, hist, compute_set_rates(hist, as_of))
        return cache[pid]

    for ev_ticker, sides in events.items():
        if len(sides) != 2:
            continue
        a, b = sorted(sides, key=lambda m: m.ticker)
        raw = a.raw or {}
        best_of = int(raw.get("_best_of", 3))
        tier = SERIES_TIER.get(raw.get("_series", ""), "15")
        pred = model.predict(a.player_a_id, b.player_a_id, None, tier,
                             MatchState(0, 0, best_of))
        if pred.confidence < 0.3:
            continue  # not enough data to say anything responsible
        try:
            prof_a, hist_a, rates_a = pdata(a.player_a_id)
            prof_b, hist_b, rates_b = pdata(b.player_a_id)
            from bot.models import Player as _P
            _tour = db.get(_P, a.player_a_id).tour
            cand = build_gameflow(
                ticker_a=a.ticker, ticker_b=b.ticker, event_ticker=ev_ticker,
                name_a=(a.raw or {}).get("yes_sub_title", "A"),
                name_b=(b.raw or {}).get("yes_sub_title", "B"),
                id_a=a.player_a_id, id_b=b.player_a_id,
                prof_a=prof_a, prof_b=prof_b, hist_a=hist_a, hist_b=hist_b,
                set_rates_a=rates_a, set_rates_b=rates_b,
                p_a=pred.p_a, best_of=best_of, start=occs.get(ev_ticker),
                as_of=as_of, model_confidence=pred.confidence,
                fatigue_a=fatigue.get(a.player_a_id),
                fatigue_b=fatigue.get(b.player_a_id),
                event_label=(a.title or "").split(":")[0].replace("Will ", ""))
            if cand is not None:
                candidates.append(cand)
        except Exception as e:
            log.warning("scenario build failed", event=ev_ticker, error=str(e))

    candidates.sort(key=lambda c: c.salience, reverse=True)
    keep = candidates[:TOP_N]
    db.execute(delete(Scenario).where(Scenario.created_for == for_day))
    for c in keep:
        db.add(Scenario(created_for=for_day, event_ticker=c.event_ticker,
                        market_ticker=c.market_ticker, player_id=c.player_id,
                        opponent_id=c.opponent_id, scenario_state=c.state_key,
                        kind=c.kind, model_prob_at_state=c.p_at_state,
                        prematch_prob=c.p_prematch, salience=c.salience,
                        narrative=c.narrative, facts=c.facts,
                        scheduled_start=c.scheduled_start,
                        created_at=datetime.now(timezone.utc)))
    db.commit()
    log.info("scenarios generated", day=str(for_day), candidates=len(candidates),
             kept=len(keep))
    return len(keep)
